# Generated by Django 5.0.3 on 2024-04-02 02:12

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("created_at", "post"),
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to=post.models.post_image_file_path,
                        verbose_name="post_image",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "posts",
                "verbose_name_plural": "posts",
                "ordering": ("created_at", "title"),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
